title: Indivisible Carson City
description: >-
  Indivisible Carson City is a local grassroots group working to promote
  progressive values and civic engagement in Carson City, Nevada.
url: "https://indivisiblecarsoncity.org"
baseurl: ""

future: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md
